# Generated by Django 5.1.5 on 2025-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_time',
            field=models.DateField(),
        ),
    ]
