# Generated by Django 5.1.5 on 2025-02-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_movie_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.CharField(choices=[('144', '144'), ('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080')], max_length=45),
        ),
    ]
